services:
  minirt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DISPLAY=host.docker.internal:0
    tty: true
    stdin_open: true
    command: /bin/bash
